name: mood_tab
description: "mood-tab 是一款专注于治愈与陪伴的跨平台个人情绪记录软件。本地数据库存储，100% 不上传云端。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  provider: ^6.1.2

  # 本地数据库
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0

  # 图表
  fl_chart: ^0.69.2

  # UI 增强
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
